
import au.com.bytecode.opencsv.CSVReader;
import javax.swing.JFileChooser;
import javax.swing.*;    
import java.awt.event.*;    
import java.io.*;
import java.sql.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class OriginalQueryLog extends javax.swing.JFrame {

String YY, MM, DD , HH , MI , SS , SEQ , THETIME , LOGID , CLIENTIP , REQUESTOR , SERVER , DBNAME , ACC , ELAPSED , BUSY , NRROWS , STATEMENT;    
    /**
     * Creates new form OriginalQueryLog
     */
    public OriginalQueryLog() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Original Query Log");

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));

        jLabel1.setText("Select the Dataset");

        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Fetch Data");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete Duplicates");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Parsing");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setText("  CLEANING ANTIPATTERNS IN  SQL QUERY LOG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(87, 87, 87)
                                .addComponent(jButton3)
                                .addGap(74, 74, 74)
                                .addComponent(jButton4))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel2)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addGap(101, 101, 101))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    JFileChooser fc=new JFileChooser();    
    int i=fc.showOpenDialog(this);    
    if(i==JFileChooser.APPROVE_OPTION){    
        File f=fc.getSelectedFile();    
        String filepath=f.getPath();    
        try{  
        BufferedReader br=new BufferedReader(new FileReader(filepath));    
        String s1="",s2="";                         
        while((s1=br.readLine())!=null){    
        s2+=s1+"\n";   
            System.out.println(s1);
            
        }    
        jTextField1.setText(filepath);    
        br.close();    
        }catch (Exception ex) {ex.printStackTrace();  } 
        
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        String csvfile="Book1.csv";
        File file=new File(csvfile);
       
        String ss=new String();
        
        try{
         
            Class.forName("com.mysql.jdbc.Driver");
    Connection conn1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/antipatterndb?useUnicode=yes&characterEncoding=UTF-8","root","info123.");
     
            PreparedStatement ps1=null,ps2=null;
            
            String s1="delete from dataset";
            String s2="delete from dataset_refined";
            ps1=conn1.prepareStatement(s1);
            ps1.executeUpdate();
           ps2=conn1.prepareStatement(s2);
            ps2.executeUpdate();
            ps1.close();
           ps2.close();
           }
                catch(Exception exp)
        {
            exp.printStackTrace();
        }    
        try{
      
            
            BufferedReader br = new BufferedReader(new FileReader(file));
         try{
       String strFile = "Book1.csv";
      CSVReader reader = new CSVReader(new FileReader(strFile));
      String [] nextLine;
      int lineNumber = 0; 
      
      while ((nextLine = reader.readNext()) != null) {
        lineNumber++;
        if(lineNumber==1)
        {
            System.out.println("\n-----Statements-----\n");
        }
        if(lineNumber!=1){
        //System.out.println("Line # " + lineNumber);
        
        System.out.println(nextLine[17]);
        
        Class.forName("com.mysql.jdbc.Driver");
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/antipatterndb?useUnicode=yes&characterEncoding=UTF-8","root","info123.");
            PreparedStatement ps=null;
            
            String s = " insert into dataset values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            ps = conn.prepareStatement(s);
            ps.setString(1, nextLine[0]);
            ps.setString(2, nextLine[1]);
            ps.setString(3, nextLine[2]);
            ps.setString(4, nextLine[3]);
            ps.setString(5, nextLine[4]);
            ps.setString(6, nextLine[5]);
            ps.setString(7, nextLine[6]);
            ps.setString(8, nextLine[7]);
            ps.setString(9, nextLine[8]);
            ps.setString(10,nextLine[9]);
            ps.setString(11,nextLine[10]);
            ps.setString(12, nextLine[11]);
            ps.setString(13, nextLine[12]);
            ps.setString(14, nextLine[13]);
            ps.setString(15, nextLine[14]);
            ps.setString(16, nextLine[15]);
            ps.setString(17, nextLine[16]);
            ps.setString(18, nextLine[17]);
            ps.executeUpdate();
         }
      }
         }
      catch(Exception yy)
              {
              yy.printStackTrace();
              }
       
       
     while ((ss = br.readLine()) != null) {
    // use comma as separator
    String[] cols = ss.split(",");
    //String[] cols1 = ss.split("");
    

          }
         }catch(Exception e){}
          
        
      

        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      
        try{
               System.out.println("\n-----After Duplicates Removal-----\n");
      Class.forName("com.mysql.jdbc.Driver");
    Connection conn2 = DriverManager.getConnection("jdbc:mysql://localhost:3306/antipatterndb","root","info123.");
     
        String ss="select distinct (SEQ), YY, MM, DD , HH , MI , SS , STATEMENT , THETIME , LOGID , CLIENTIP , REQUESTOR , SERVER , DBNAME , ACC , ELAPSED , BUSY , NRROWS from dataset";
         
    Statement st;
    ResultSet rs;
             st=conn2.createStatement();
             rs=st.executeQuery(ss);
             while(rs.next())
            {
                           
                YY=rs.getString(2);
                MM=rs.getString(3);
                DD=rs.getString(4);
                HH=rs.getString(5);
                MI=rs.getString(6);
                SS=rs.getString(7);
                STATEMENT=rs.getString(8);
                THETIME=rs.getString(9);
                LOGID=rs.getString(10);
                CLIENTIP=rs.getString(11);
                REQUESTOR=rs.getString(12);
                SERVER=rs.getString(13);
                DBNAME=rs.getString(14);
                ACC=rs.getString(15);
                ELAPSED=rs.getString(16);
                BUSY=rs.getString(17);
                NRROWS=rs.getString(18);
                        SEQ=rs.getString(1);
               
                  try{

                       // static int k=1;
                      
                      Class.forName("com.mysql.jdbc.Driver");
    Connection conn3 = DriverManager.getConnection("jdbc:mysql://localhost:3306/antipatterndb","root","info123.");
                    
                PreparedStatement pst=null;
                String str="insert into dataset_refined values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                 pst= conn3.prepareStatement(str);
                 pst.setString(1,YY );
                 pst.setString(2,MM );
                 pst.setString(3,DD);
                 pst.setString(4, HH);
                 pst.setString(5,MI );
                 pst.setString(6,SS);
                 pst.setString(7,SEQ);
                 pst.setString(8,THETIME);
                 pst.setString(9,LOGID);
                 pst.setString(10,CLIENTIP);
                 pst.setString(11,REQUESTOR);
                pst.setString(12,SERVER);
                pst.setString(13,DBNAME);
                pst.setString(14,ACC);
                pst.setString(15,ELAPSED);
                pst.setString(16,BUSY);
                pst.setString(17,NRROWS);
                pst.setString(18,STATEMENT);
                pst.execute();
               
                pst.close();
                conn3.close();
                 }catch(Exception ff)
                    {
                ff.printStackTrace();
                        }
 System.out.println(STATEMENT);
      
  }
                  }
                  catch(Exception e)
                  {
                      e.printStackTrace();
                  }
     
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       try{ 
        String[] arguments = new String[] {"123"};
        Main1.main(arguments);
        }
       catch(Exception ere)
       {
           
       }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OriginalQueryLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OriginalQueryLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OriginalQueryLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OriginalQueryLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OriginalQueryLog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
